### ISSUE TITLE
Kopírovaní domény ze stránky uzivZona

### ISSUE THREAD

**Issue by Ardn0** [petrvavra420/bswsProjekt#91]
Když zkopíruju celou doménu (moje doména + sever doména) na stránce uzivZona a vložím do url je tam mezera a danou doménu to nenajde, protože to neexistuje.

Viz. petamaster .skola.pokus nebo ondratest .skola.pokus ->na účtu admin

**Comment by petrvavra420** [comment]
Nevím jak replikovat, u mě na lokálu nebo na serveru zkopíruju bez mezery

**Comment by petrvavra420** [comment]
Už to vidím, je to blbost neřešil bych - ale udělal jsem z těch domén odkazy kde každá z nich odkazuje na jejich příslušnou stránku - closed caf
